[workspace]
resolver = "2"
members = ["api", "workers"]

[workspace.dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
